import { Providers } from "@/app/providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Clon de twitter",
  description: "Generated by create next app",
};

export default function SignInSignUpLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <section>
        
        {children}
        </section>
        </Providers>
  );
}