import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "./navbar/navbar";

export const metadata: Metadata = {
  title: "Clon de twitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="w-full h-dvh flex">
          <Navbar />
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
