import type { Metadata } from "next";


import Navbar from "@/app/components/navbar/navbar";

export const metadata: Metadata = {
  title: "Clon de twitter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className="w-full h-dvh flex">
        <Navbar />
        {children}
    </section>
  );
}
